### ISSUE TITLE
Doesn't work in python 3.10

### ISSUE THREAD

**Issue by wk9874** [simvue-io/python-api#986]
## Description of Bug
Python API  crashes on python 3.10, since it uses timezone.UTC, which is an alias that was only introduced in 3.11.
## Steps To Reproduce
1. Try running it on 3.10

## Expected behavior
Runs correctly

## Actual Behaviour
```
    from simvue.config.user import SimvueConfiguration
../../../Library/Caches/pypoetry/virtualenvs/simvue-moose-SyxDCI6N-py3.10/lib/python3.10/site-packages/simvue/config/user.py:39: in <module>
    from simvue.eco.config import EcoConfig
../../../Library/Caches/pypoetry/virtualenvs/simvue-moose-SyxDCI6N-py3.10/lib/python3.10/site-packages/simvue/eco/__init__.py:11: in <module>
    from .emissions_monitor import CO2Monitor as CO2Monitor
../../../Library/Caches/pypoetry/virtualenvs/simvue-moose-SyxDCI6N-py3.10/lib/python3.10/site-packages/simvue/eco/emissions_monitor.py:41: in <module>
    class CO2Monitor(pydantic.BaseModel):
../../../Library/Caches/pypoetry/virtualenvs/simvue-moose-SyxDCI6N-py3.10/lib/python3.10/site-packages/simvue/eco/emissions_monitor.py:82: in CO2Monitor
    _last_local_write = pydantic.PrivateAttr(datetime.datetime.now(tz=datetime.UTC))
E   AttributeError: module 'datetime' has no attribute 'UTC'
```

**Comment by kzscisoft** [comment]
Should be fixed now closing
